Turn on both valgrind tests

diff --git a/continuous_integration/standard_build b/continuous_integration/standard_build
--- a/continuous_integration/standard_build
+++ b/continuous_integration/standard_build
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/sh -x
 
 debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
 log() { printf '%s\n' "$*"; }
@@ -63,22 +63,22 @@ cd "${mydir}"
     || fatal "Error transforming test valgrind output"
 
 
-#NOT WORKING # run valgrind on the executable
-#NOT WORKING cd "${WORKSPACE}"
-#NOT WORKING START=$(date +%s)
-#NOT WORKING valgrind --track-fds=yes --leak-check=full --track-origins=yes \
-#NOT WORKING     --error-limit=no \
-#NOT WORKING     --xml=yes --xml-file="${mydir}/rootsh-valgrind.xml" \
-#NOT WORKING     --gen-suppressions=all --suppressions="${mydir}/valgrind_suppression_rules.txt" \
-#NOT WORKING     "src/rootsh" -c ls || fatal "Error running valgrind on tests"
-#NOT WORKING END=$(date +%s)
-#NOT WORKING DURATION=$(( ${END} - ${START} ))
-#NOT WORKING sleep 1
-#NOT WORKING cd "${mydir}"
-#NOT WORKING ./xUnit/transform_valgrind.py \
-#NOT WORKING     -i rootsh-valgrind.xml \
-#NOT WORKING     -o rootsh-valgrind.TEST.xml -d ${DURATION} \
-#NOT WORKING     || fatal "Error transforming rootsh valgrind output"
+# run valgrind on the executable
+cd "${WORKSPACE}"
+START=$(date +%s)
+valgrind --track-fds=yes --leak-check=full --track-origins=yes \
+    --error-limit=no \
+    --xml=yes --xml-file="${mydir}/rootsh-valgrind.xml" \
+    --gen-suppressions=all --suppressions="${mydir}/valgrind_suppression_rules.txt" \
+    "src/rootsh" -c ls || fatal "Error running valgrind on tests"
+END=$(date +%s)
+DURATION=$(( ${END} - ${START} ))
+sleep 1
+cd "${mydir}"
+./xUnit/transform_valgrind.py \
+    -i rootsh-valgrind.xml \
+    -o rootsh-valgrind.TEST.xml -d ${DURATION} \
+    || fatal "Error transforming rootsh valgrind output"
 
 
 ${mydir}/copy-paste-detector || fatal "Error running copy paste detect"
